montage_path: "C:/Users/greg/Documents/masters/matlab_extensions/eeglab14_1_1b/plugins/dipfit2.3/standard_BESA/standard-10-5-cap385"
raw_vhdr: "C:/Users/greg/Documents/masters/subjects/SC/eeg-fmri/eeg/anticip_1206sc03_01_005.vhdr"