montage_path: "C:/Users/greg/Documents/masters/matlab_extensions/eeglab14_1_1b/plugins/dipfit2.3/standard_BESA/standard-10-5-cap385.elp"
raw_gradrem_fif: "data-path-to-gradrem-fif"

output: "output"
debug-plot: False
display_ica_components: True