montage_path: "C:/Users/greg/Documents/masters/matlab_extensions/eeglab14_1_1b/plugins/dipfit2.3/standard_BESA/standard-10-5-cap385.elp"
raw_vhdr: "data-path"
alignment_trigger_name: '80'
slice_gradient_similarity_correlation:  0.9

output: "output-location"