montage_path: "C:/Users/greg/Documents/masters/matlab_extensions/eeglab14_1_1b/plugins/dipfit2.3/standard_BESA/standard-10-5-cap385.elp"
data_path: "path-to-data"
alignment_trigger_name: '80'
slice_gradient_similarity_correlation:  0.9

debug-plot: False
display_ica_components: True
output: "output-location"